# Generated by Django 5.0.2 on 2024-02-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_courses_to_professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
