# Generated by Django 5.0.2 on 2024-02-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_link_courses_to_professors_alter_courses_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link_courses_to_professors',
            new_name='c_to_p',
        ),
    ]
