# Generated by Django 5.0.2 on 2024-02-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_link_courses_to_professors_c_to_p'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c_to_p',
            new_name='CtoP',
        ),
    ]
