# Generated by Django 5.0.2 on 2024-03-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_professorslimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorslimit',
            old_name='Professor',
            new_name='professor',
        ),
    ]
