# Generated by Django 5.0.2 on 2024-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_rename_professor_professorslimit_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
