# Generated by Django 5.0.2 on 2024-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_courses_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
